### ISSUE TITLE
Please provide the full detailed description of the project in README.md

### ISSUE THREAD

**Issue by akkyjumbade** [123govind46/myfirstproject#2]
Specify the detailed description and guide of the project in README.md

**Comment by akkyjumbade** [comment]
tak kahi tari dummy doc

**Comment by 123govind46** [comment]
what would you want to resolve in this project

**Comment by akkyjumbade** [comment]
tak kahi tari dummy doc

**Comment by akkyjumbade** [comment]
Update in README.md
